services:
  web-socker:
    build:
      context: .
      dockerfile: ./infra/local/Dockerfile
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
      AWS_PROFILE: "default"
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/usr/src/app

volumes:
  node_modules: